FROM node:20
WORKDIR /app

# Install deps
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose port 80
EXPOSE 80

# Run vite dev server on port 80
CMD ["npm", "run", "dev", "--", "--host", "--port", "80"]
