version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "8080:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_BASE=http://localhost:4500/api
    command: ["npm", "run", "dev", "--", "--host", "--port", "80"]
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "4500:4500"
    environment:
      - MONGO_URL=mongodb://mongo:27017/whatnotdb
    command: ["npm", "run", "dev"]
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  seed:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - MONGO_URL=mongodb://mongo:27017/whatnotdb
    command: ["node", "seed.js"]
    depends_on:
      - mongo

volumes:
  mongo_data:
