version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app
    ports:
      - "8080:80"
    env_file:
      - ./client/.env.development   # 👈 loads client vars
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: ["npm", "run", "dev", "--", "--host", "--port", "80"]
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
    ports:
      - "4500:4500"
    env_file:
      - ./server/.env.development   # 👈 loads server vars
    command: ["npm", "run", "dev"]
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  seed:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env.development   # 👈 same as server
    command: ["node", "seed.js"]
    depends_on:
      - mongo

volumes:
  mongo_data:
